"""initial_schema_with_indexes

Revision ID: 5abbf2fc8477
Revises: 
Create Date: 2026-06-08 16:39:14.350401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abbf2fc8477'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_codes_id'), ['id'], unique=False)

    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_user_id'), ['user_id'], unique=False)

    op.create_table('imported_portfolio_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('security_name', sa.String(length=80), nullable=True),
    sa.Column('current_position', sa.Float(), nullable=True),
    sa.Column('available_position', sa.Float(), nullable=True),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('current_position_pct', sa.Float(), nullable=True),
    sa.Column('trade_points_json', sa.JSON(), nullable=True),
    sa.Column('trade_points_count', sa.Integer(), nullable=False),
    sa.Column('latest_trade_at', sa.String(length=32), nullable=True),
    sa.Column('latest_trade_action', sa.String(length=16), nullable=True),
    sa.Column('last_imported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'symbol', name='uq_imported_portfolio_user_source_symbol')
    )
    with op.batch_alter_table('imported_portfolio_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_portfolio_positions_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('risk_items', sa.JSON(), nullable=True),
    sa.Column('key_metrics', sa.JSON(), nullable=True),
    sa.Column('analyst_traces', sa.JSON(), nullable=True),
    sa.Column('market_report', sa.Text(), nullable=True),
    sa.Column('sentiment_report', sa.Text(), nullable=True),
    sa.Column('news_report', sa.Text(), nullable=True),
    sa.Column('fundamentals_report', sa.Text(), nullable=True),
    sa.Column('macro_report', sa.Text(), nullable=True),
    sa.Column('smart_money_report', sa.Text(), nullable=True),
    sa.Column('volume_price_report', sa.Text(), nullable=True),
    sa.Column('game_theory_report', sa.Text(), nullable=True),
    sa.Column('investment_plan', sa.Text(), nullable=True),
    sa.Column('trader_investment_plan', sa.Text(), nullable=True),
    sa.Column('final_trade_decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('scheduled_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=True),
    sa.Column('trigger_time', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_date', sa.String(length=10), nullable=True),
    sa.Column('last_run_status', sa.String(length=10), nullable=True),
    sa.Column('last_report_id', sa.String(length=36), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_scheduled_user_symbol')
    )
    with op.batch_alter_table('scheduled_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('sponsors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sponsor_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('github', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_sponsor_type'), ['sponsor_type'], unique=False)

    op.create_table('user_llm_configs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('backend_url', sa.String(length=500), nullable=True),
    sa.Column('quick_think_llm', sa.String(length=255), nullable=True),
    sa.Column('deep_think_llm', sa.String(length=255), nullable=True),
    sa.Column('max_debate_rounds', sa.Integer(), nullable=True),
    sa.Column('max_risk_discuss_rounds', sa.Integer(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('wecom_webhook_encrypted', sa.Text(), nullable=True),
    sa.Column('default_analysts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_llm_configs_user_id'), ['user_id'], unique=False)

    op.create_table('user_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('token_hint', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('email_report_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('wecom_report_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('version_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=True),
    sa.Column('remote_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_stats_remote_ip'), ['remote_ip'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('version_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_stats_remote_ip'))

    op.drop_table('version_stats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_user_tokens_id'))

    op.drop_table('user_tokens')
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_llm_configs_user_id'))

    op.drop_table('user_llm_configs')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_sponsor_type'))
        batch_op.drop_index(batch_op.f('ix_sponsors_id'))

    op.drop_table('sponsors')
    with op.batch_alter_table('scheduled_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_analyses_user_id'))

    op.drop_table('scheduled_analyses')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_symbol'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('imported_portfolio_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_portfolio_positions_user_id'))

    op.drop_table('imported_portfolio_positions')
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_id'))

    op.drop_table('feedbacks')
    with op.batch_alter_table('email_verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_codes_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_codes_email'))

    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
